### ISSUE TITLE
How does this catch a fatal crash from Phonegap?

### ISSUE THREAD

**Issue by jnorris441** [sarriaroman/FabricPlugin#1]
Are you calling sendCrashWithData when you get a Javascript error, or are you detecting a native crash somehow?

**Comment by sarriaroman** [comment]
The native crash is detected automatically by the Fabric SDK installed on your app. The method described is pretended to send extra data from JS or simulate a crash with information. An example of sending a crash is a catch error from JS that you want to be notified in the moment by Fabric.

**Comment by jnorris441** [comment]
Thanks
