### ISSUE TITLE
Can't get it to work for iOS (Ionic 2+ app)

### ISSUE THREAD

**Issue by zarko-tg** [sarriaroman/FabricPlugin#118]
First of all it took a while (after numerous builds/runs of the iOS app) to have it appear in the Fabric Crashlytics dashboard, unlike the one for Android.
And now it won't show any events registered in the iOS project dashboard, even though we test by calling addLog, sendNonFatalCrash and sendCrash functions.

We build strictly via command line and building for iOS results in no errors on the console. Our builds are fully repeatable each time - platforms and plugins re-created each time.

Android works well, just as expected.

The plugin is configured in the project via the config.xml such as in:
```
  <plugin name="cordova-fabric-plugin" spec="1.1.10">
    <variable name="FABRIC_API_KEY" value="FOO"/>
    <variable name="FABRIC_API_SECRET" value="BAR"/>
  </plugin>
```

___
    cordova (Cordova CLI): 6.5.0 
    Cordova Platforms: ios 4.5.4
    Ionic Framework: ionic-angular 3.9.2

    Node: v8.9.1
    npm: 5.6.0 
    OS: macOS High Sierra
    Xcode: Xcode 9.2 Build version 9C40b

**Comment by birfincankafein** [comment]
Same +1

**Comment by tbergeron** [comment]
Before I start using this for an Ionic cross-platform project, does this happen often when using this plugin with Ionic 2+? Has this been resolved yet? Thanks and good luck.
