### ISSUE TITLE
cordova-android 7.0.0: fabric plugin applied before 'com.android.application'

### ISSUE THREAD

**Issue by 814k31** [sarriaroman/FabricPlugin#119]
I have this issue when trying to upgrade to cordova-android 7.0.0 from 6.4
I believe the structure is different where the bulk of the gradle script have been moved to platforms/android/app/build.gradle

Have you got any suggestions on getting this to work?
cordova-fabric-plugin is still installed under platforms/android

**Comment by raul-handpoint** [comment]
Please, take a look at this issue I opened recently. I think this is the same problem:

https://github.com/sarriaroman/FabricPlugin/issues/120
