### ISSUE TITLE
disable?

### ISSUE THREAD

**Issue by csabbey** [sarriaroman/FabricPlugin#158]
My app expires, but some people aren't uninstalling it. Is there a way to disable Crashlytics, so I stop seeing errors for these users?

**Comment by amymarsh4work** [comment]
You need to go into the Fabric dashboard, find where you can change settings for your project (upper right). Then, you should see a bunch of releases of your app with version numbers, and toggle switches. Turn off the toggle for the old versions that you want to disable.

**Comment by csabbey** [comment]
Thanks, but I wanted to disable it for individual phones when the app
expires, not disable it for everyone. I was hoping there was some
programmatic way of disabling it on the app side.

**Comment by amymarsh4work** [comment]
In that case, I have tons more questions and it would be very time consuming for me to ask them all. I think your best way forward is to close this thread, and ask your question differently in a new one.

It would help to know the scenario you are dealing with, very specifically. Why do you want some users but not others to be running the same released version, yet some be expected to uninstall? See how this is confusing? 

Start a new thread and give as much explanation and detail as possible (the business case), along with what platforms like Firebase or Ionic AppFlow your app is using that could be used to change the way the app behaves remotely. Maybe then someone will understand your problem and be able to help.

**Comment by craig-at-rsg** [comment]
It's actually not complicated - our app collects data from users for a few days, and we send them a gift card for their participation. We ask them to uninstall when the study is over through multiple methods (in-app popups, email, and paper instructions we mail out), but people still have the app on their phone years later, and we don't bother maintaining that much backwards compatibility (people are getting upgrades to newer versions that get errors because the existing in-app data isn't compatible). We silence other communications from the app, but we haven't found a way to silence Crashlytics.

**Comment by amymarsh4work** [comment]
OK, brainstorming options here, given the info I have:

- Wait for one of the maintainers to chime in
- Create a new release of your app that clears out the in-app data, causing crashes
- Remove Crashlytics from the app and abandon the account sending you emails. Reinstall it, setup a new Firebase Crashlytics account under new app IDs for your target platforms. This will get rid of your past headache. Then, think of how to prevent it from happening again.
- Fork the plugin yourself, figure out how it works well enough that you could silence it and then release a new version of your app with it installed (I'm not kidding. I have forked this repo to be able to get a fix to users from a PR that was waiting approval)

Your problem *seems* simple to solve. It's time based. Unfortunately, I don't have much to go on. Are you collecting device ids and when they originally installed? Seems like a challenge would be a crash scenario immediately upon launching the app and how to prevent that. If you accomplished that, you could prevent the app from running other code that could result in errors. It would basically do nothing but show a landing screen of 'disabled - uninstall me'.

Best I can do.

**Comment by amymarsh4work** [comment]
I'd just add that we have this happening too, except the errors I see are for users that are running a version of the app that is months and months behind what's current. If you fail to get the help you need, you could investigate how to at least filter out the crashes you care about, and ignore the ones causing noise.

**Comment by csabbey** [comment]
Thanks for your help, Amy.

**Comment by csabbey** [comment]
From https://stackoverflow.com/a/49546854/2199492:
The Firebase Crashlytics documentation explains that once reporting is enabled in an app session, it cannot be disabled.

So my answer is don't initialize it after my app expires.
