### ISSUE TITLE
Run Script Path Issue

### ISSUE THREAD

**Issue by dparne** [sarriaroman/FabricPlugin#17]
Hi,

The run script generated when we do "ionic platform add ios" has the path to Crashlytics framework as

plugins/com.sarriaroman.fabric/lib/ios/Crashlytics.framework but in fact the path getting generated is

plugins/com.sarriaroman.fabric/Crashlytics.framework. 

This is causing failures in CI tools.

am I doing something wrong here?

Thanks,
Dinesh

**Comment by Justin-Credible** [comment]
Can you provide steps to reproduce?

**Comment by dparne** [comment]
I have these steps in my script (I am using circle ci) and I ran same steps locally.

```
dependencies:
  pre:
    - brew uninstall xctool && brew install --HEAD xctool
    - brew install node
    - npm install
    - npm install -g ionic
    - npm install -g cordova
    - npm install -g gulp
    - gulp
    - ionic hooks add
    - cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=$MY_KEY --variable FABRIC_API_SECRET=$MY_SECRET
    - ionic platform rm ios
    - ionic platform add ios
```

and this results in this run script

![screen shot 2016-03-11 at 5 42 16 pm](https://cloud.githubusercontent.com/assets/1863682/13718570/c99ba66a-e7b0-11e5-9c8a-b4125425a1e1.png)

Where as in the file system I see this 
<img width="545" alt="screen shot 2016-03-11 at 5 44 25 pm" src="https://cloud.githubusercontent.com/assets/1863682/13718588/ef9a6b8a-e7b0-11e5-95a6-d81c834534fc.png">

you can notice that ```lib/ios``` folders are not there

**Comment by Justin-Credible** [comment]
If that Finder screenshot is of `platforms/ios/your-app/Plugins`, then it looks correct. The script itself is referencing files outside of the XCode project. The path `../../plugins/com.sarriaroman.fabric/lib/ios/Crashlytics.framework/run` is pointing two directories up from the XCode project root. So this is `<cordova-root>/plugins` which does contain the `lib/ios/` path.

You can verify this by changing the path in the build script to something invalid and XCode build will fail.

What error message are you receiving?

**Comment by dparne** [comment]
Hi @Justin-Credible. I found the root cause now. Thanks for the explanation.

I was running this command in the root folder instead of ios folder.

xctool CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= -sdk iphoneos9.2 -project ./platforms/ios/MyProject.xcodeproj -scheme "MyProject" clean build

Since I was in the root the shell script was looking outside of the root folder and not finding the plugin.
