### ISSUE TITLE
is there any way to specify fabric distribution properties with this plugin?

### ISSUE THREAD

**Issue by karser** [sarriaroman/FabricPlugin#28]
I'm uploading a build to Crashlytics with the following command:
```
./gradlew assembleRelease crashlyticsUploadDistributionArmv7Release
```
As it's described [here](http://support.crashlytics.com/knowledgebase/articles/388925-beta-distributions-with-gradle) it's possible to specify distribution group and release notes:
```
ext.betaDistributionReleaseNotes=”Release Notes for this build.”
ext.betaDistributionEmails="BetaUser@y.com, BetaUser2@y.com"
ext.betaDistributionGroupAliases=”my-best-testers”
```

The only way to do that now is to [create build-extras.gradle](https://cordova.apache.org/docs/en/5.0.0/guide/platforms/android/tools.html)
```
If you need to customize build.gradle, rather than edit directly, you should create a sibling file named build-extras.gradle. This file will be included by the main build.gradle when present.
```

**Comment by Justin-Credible** [comment]
I upload my APKs to Crashlytics using the `crashlytics-devtools.jar` at the command line which supports groups and release notes.

You can get a list of all of the command line switches by using the `--help` switch:

```$ java -jar resources/android/crashlytics-devtools.jar --help```

**Comment by karser** [comment]
Thanks. Is it Crashlytics Ant plugin? https://docs.fabric.io/android/crashlytics/ndk.html#crashlytics-additions-to-ant-projects

**Comment by Justin-Credible** [comment]
Yes, you can get the jar by downloading the Ant package from https://fabric.io/downloads/ant.

You don't actually have to use the Ant build scripts to use the jar though. I use the jar directly solely for uploading builds from the CLI.

**Comment by joejensen8** [comment]
I'm trying to use the crashlytics dev tools jar to upload a beta apk file to Fabric, but get an illegal argument exception that I'm missing a required parameter. What parameters are you using on the command line?
