### ISSUE TITLE
Plugin id different from npm package name

### ISSUE THREAD

**Issue by mircoc** [sarriaroman/FabricPlugin#30]
When i install the plugin from npm it keep installing everytime i run cordova prepare:

`
Discovered plugin "cordova-fabric-plugin" in config.xml. Installing to the project
Fetching plugin "cordova-fabric-plugin@~1.0.5" via npm
Plugin "com.sarriaroman.fabric" already installed on android.
Plugin "com.sarriaroman.fabric" already installed on ios.
`

I installed the plugin adding this in my config.xml:
`
    <plugin name="cordova-fabric-plugin" spec="~1.0.5">
        <variable name="FABRIC_API_KEY" value="xxx" />
        <variable name="FABRIC_API_SECRET" value="xxx" />
    </plugin>
`

In plugin.xml i see the id is:
`
<plugin id="com.sarriaroman.fabric" version="1.0.5" xmlns="http://www.phonegap.com/ns/plugins/1.0">
`

I think this is because the plugin id is different from the npm package name.

Is it reasonable to change the plugin id to **cordova-fabric-plugin**?

**Comment by sarriaroman** [comment]
Fixed on version 1.0.6. Feel free to close the issue once you made some try.

**Comment by sarriaroman** [comment]
Solved with version 1.0.7
