### ISSUE TITLE
How to get "API Key and Build Secret"?

### ISSUE THREAD

**Issue by atgillette** [sarriaroman/FabricPlugin#36]
The instructions for getting the API Key and Build Secret does not work for me.  After creating a Fabric account, I have to download the xcode plugin.  How can I just define a new app on the Fabric.io site without going thru xcode?

**Comment by Justin-Credible** [comment]
It appears that this currently is a limitation of the Fabric website. New users are locked to the onboarding URL and cannot get to their keys until the xcode plugin etc is manually integrated.

I've posted on Fabric's forms about this [issue](https://twittercommunity.com/t/cant-get-fabric-api-key/61490/7).

As a workaround, you can create a blank iOS or Android app from Xcode/Android Studio, integrate the IDE plugin with your blank project and launch it. This will allow you to get into the rest of the Fabric website where you can obtain your keys.

You can then use the keys for your Cordova app with this plugin, and once integrated, delete the blank project we added to Fabric earlier.

**Comment by atgillette** [comment]
@Justin-Credible,

Thanks for your your solution!  I'll give that a try.

**Comment by atgillette** [comment]
@Justin-Credible,

I accidentally removed the build scripts from the build phases in xcode.  How can I execute the "after_plugin_install.js" again?

**Comment by Justin-Credible** [comment]
cordova plugin remove cordova-fabric-plugin
    cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=XXX --variable FABRIC_API_SECRET=xxx

**Comment by atgillette** [comment]
Thanks again @Justin-Credible

**Comment by Justin-Credible** [comment]
No problem.

Just for future reference it looks like you can get your Fabric api key/secret from this page even if you haven't add an app yet.

https://fabric.io/kits/ios/crashlytics/install

**Comment by bommaka** [comment]
//add this in  tsconfig.json
 "files": [ "plugins/cordova-fabric-plugin/typings/cordova-fabric-plugin.d.ts" ]

// add this in angular project
declare var fabric;
var attributes = {
      foo: "data",
      bar: true,
   };
    fabric.Crashlytics.addLog("about to send a crash for testing!");
    fabric.Answers.sendSignUp("Facebook", true, attributes);  

Result:
<img width="1187" alt="screen shot 2018-05-04 at 6 44 07 pm" src="https://user-images.githubusercontent.com/4052972/39629912-559cee2e-4fcb-11e8-9e51-91f1131e038d.png">
