### ISSUE TITLE
Your fabric.properties file is missing your build secret.

### ISSUE THREAD

**Issue by MHV1** [sarriaroman/FabricPlugin#39]
I created a Cordova project and added the Android platform and the cordova-fabric- plugin with my Facric.io keys (both API and Secret). Then I build the project.

When executing gradlew task 'crashlyticsUploadDistributionDebug' on Windows command line I keep getting the following error: 
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Your fabric.properties file is missing your build secret.

When looking at the platforms/android folder the fabric.properties file is missing. I don't know if it is a problem when building the project.

What could be the problem?

**Comment by Justin-Credible** [comment]
I would double check that you've added the plugin **after** you've added your platforms so that the build hooks can update the platform files properly.

Here are the steps I used to try and reproduce your problem:

````
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

D:\Development>npm install cordova -g
C:\Users\Justin\AppData\Roaming\npm\cordova -> C:\Users\Justin\AppData\Roaming\npm\node_modules\cordova\bin\cordova
cordova@6.1.1 C:\Users\Justin\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── ansi@0.3.1
├── nopt@3.0.1 (abbrev@1.0.7)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, chalk@1.1.3, repeating@1.1.3,
configstore@1.4.0, latest-version@1.0.1)
├── cordova-common@1.2.0 (cordova-registry-mapper@1.1.15, q@1.4.1, underscore@1.8.3, unorm@1.4.1, semver@5.1.0, osenv@0.1.3, shelljs@0.5.3, bplist-parser@0.1.1, glob@5.0.15, elementtree@0.1.6, plist@1.2.0)
└── cordova-lib@6.1.1 (valid-identifier@0.0.1, opener@1.4.1, properties-parser@0.2.3, semver@4.3.6, nopt@3.0.6, dep-graph@1.1.0, shelljs@0.3.0, xcode@0.8.0, request@2.47.0, aliasify@1.9.0, tar@1.0.2, init-package-json@1.9.3, cordova-app-hello-world@3.10.0, cordova-serve@1.0.0, cordova-js@4.1.4, npm@2.15.5)

D:\Development>node --version
v4.2.4

D:\Development>cordova --version
6.1.1

D:\Development>cd Temp

D:\Development\Temp>cordova create TestApp6
Creating a new cordova project.

D:\Development\Temp>cd TestApp6

D:\Development\Temp\TestApp6>cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-23
Android project created with cordova-android@5.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.


D:\Development\Temp\TestApp6>cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=xxx --variable FABRIC_API_SECRET=xxx
Fetching plugin "cordova-fabric-plugin" via npm
Installing "cordova-fabric-plugin" for android

D:\Development\Temp\TestApp6>cordova prepare android

D:\Development\Temp\TestApp6>cordova build android

# Lots of build output here

Total time: 1 mins 36.681 secs
Built the following apk(s):
        D:/Development/Temp/TestApp6/platforms/android/build/outputs/apk/android-debug.apk

D:\Development\Temp\TestApp6>

````

**Comment by MHV1** [comment]
I have tried the same steps you mentioned but still no luck. These are the steps I performed:

C:\Users\Milan\Documents\Cordova>cordova create TestApp
Creating a new cordova project.

C:\Users\Milan\Documents\Cordova>cd TestApp

C:\Users\Milan\Documents\Cordova\TestApp>cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-23
Android project created with cordova-android@5.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

C:\Users\Milan\Documents\Cordova\TestApp>cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=XXXXX --variable FABRIC_API_SECRET=XXXXX
Fetching plugin "cordova-fabric-plugin" via npm
Installing "cordova-fabric-plugin" for android

C:\Users\Milan\Documents\Cordova\TestApp>cordova prepare android

C:\Users\Milan\Documents\Cordova\TestApp>cordova build android
--Output Omitted--

BUILD SUCCESSFUL
Total time: 18.541 secs
Built the following apk(s):
        C:/Users/Milan/Documents/Cordova/TestApp/platforms/android/build/outputs/apk/android-debug.apk

C:\Users\Milan\Documents\Cordova\TestApp>cd platforms/android

C:\Users\Milan\Documents\Cordova\TestApp\platforms\android>gradlew.bat
--Output Omitted--

BUILD SUCCESSFUL
Total time: 6.204 secs

C:\Users\Milan\Documents\Cordova\TestApp\platforms\android>gradlew.bat crashlyticsUploadDistributionDebug
:crashlyticsUploadDistributionDebug
Uploading C:\Users\Milan\Documents\Cordova\TestApp\platforms\android\build\outputs\apk\android-debug.apk to Crashlytics...
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Your fabric.properties file is missing your build secret.
Check the Crashlytics plugin to make sure that the application has been added successfully!
Contact support@fabric.io for assistance.

--Output Omitted--

:crashlyticsUploadDistributionDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':crashlyticsUploadDistributionDebug'.
> Crashlytics Developer Tools error.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 6.0 secs

I was thinking I'm probably missing someting. This is the first time I use Cordova so I'm not to familiar with the build process or anything else that isn't in the Cordova documentation.

Thank you for your help.

**Comment by MHV1** [comment]
BTW, What I want to do is run the script on a CI server (Jenkins) in order to automate the beta distribution of the app. One of my workmates manged to get it working on iOS following these steps:

```
cordova platform add ios
cordova plugin add cordova-fabric-plugin --variable FABRIC_API_KEY=XXXXX --variable FABRIC_API_SECRET=XXXXX
cordova build ios

./platforms/ios/CordovaExamples/Plugins/cordova-fabric-plugin/Crashlytics.framework/submit XXXXX -emails name@mail.com -notifications YES -ipaPath ./platforms/ios/build/device/example.ipa
```

But we think the steps might be quite different for Android since Gradle works different.

**Comment by Justin-Credible** [comment]
Ah, sorry. I missed the fact that you are trying to upload your build.

Below is the command I use to upload my APKs to Crashlytics. You'll need the `crashlytics-devtools.jar` file which has the upload command. You can also optionally specify your release notes this way.

````
java -jar resources/android/crashlytics-devtools.jar -apiSecret xxx -apiKey xxx -verbose -projectPath platforms/android -androidManifest platforms/android/AndroidManifest.xml -androidRes platforms/android/res -androidAssets platforms/android/assets -requireUploadSuccess -uploadDist platforms/android/build/outputs/apk/android-armv7-release.apk -betaDistributionReleaseNotesFilePath resources/android/beta-release-notes.txt
````

**Comment by MHV1** [comment]
I have downloaded the 'crashlytics-devtools.jar' file from Fabric.io (unless there is another way of getting it?) and followed these steps:

```
C:\Users\Milan\Documents\Cordova\TestApp>cordova build android –debug

C:\Users\Milan\Documents\Cordova\TestApp>java -jar crashlytics-devtools.jar -apiSecret XXXXX -apiKey XXXXX -verbose -projectPath platforms/android -androidManifest platforms/android/AndroidManifest.xml -androidRes platforms/android/res -androidAssets platforms/android/assets -requireUploadSuccess -uploadDist platforms/android/build/outputs/apk/android-debug.apk

C:\Users\Milan\Documents\Cordova\TestApp>
```

The command seems to be successful but I cannot see the application in Fabric.io. I don’t know if I’m missing anything. I read in the Fabric documentation that the 'crashlytics-devtools.jar' is necessary when using Ant and not Gradle, but I don't know if it makes any difference.

**Comment by Justin-Credible** [comment]
You should already be able to see your app in the Fabric console. If it isn't showing up there, even before uploading a build, then the plugin may not be installed correctly.

After installing the plugin and launching the app for the first time, you should be able to see your app in the Fabric dashboard or at the top left drop down in Fabric.

**Comment by MHV1** [comment]
Great! It works now. The problem was that I wasn't launching the app at all. I thought that only building it would be enough, just like in iOS (as I showed in one of my previous comments).

One last thing: Is it possible to upload the build without having to launch the application in a device or emulator? Like I said before, I'm automating the process using a CI server and I don't have a way of running the app there.
Thank you very much for your help anyway.

**Comment by Justin-Credible** [comment]
You only have to run the app once for each platform (iOS and Android) for it to show up in the Fabric dashboard. After that you can simply use the command line tools (`Crashlytics.framework/submit` and `crashlytics-devtools.jar`) to upload builds without launching the app again.

Glad you got it working!
