### ISSUE TITLE
sendContentView & sendCustomEvent doesn't work

### ISSUE THREAD

**Issue by ivelfan** [sarriaroman/FabricPlugin#42]
Hello,

I recently created a new cordova projet with the latest version.
I added this plugin to try Fabric engine and after many tests on Android platform, I couldn't send Content View event or Custom event.
Others works.
No errors in JavaScript Console.

Do you have an idea to fix this ?

Thanks.

**Comment by hungdoan2** [comment]
Did your app appear in fabric dashboard ?
Try to login to https://fabric.io/login
Make sure your app is listed in https://fabric.io/settings/apps .

**Comment by ivelfan** [comment]
Sorry, I forgot this thread.

My app is visible in the apps list.
I can send all of the event with my App, but only Content View event isn't send.
