### ISSUE TITLE
armv7 and x86 apks

### ISSUE THREAD

**Issue by atgillette** [sarriaroman/FabricPlugin#43]
This is a question about how to make these available to beta users.  Do I need to create two android apps?

**Comment by hungdoan2** [comment]
What do you mean ?

**Comment by atgillette** [comment]
@hungdoan2,

I think I figured this out.  When I do a cordova build android, it generates two apk files, one for arm and one for x86.  I learned that I can create a single apk file that is suitable for both architectures.  I just need to create a `build-extras.gradle` and add this:
`cdvBuildMultipleApks=false`
