### ISSUE TITLE
App-restart required for errors to show up

### ISSUE THREAD

**Issue by FabianAlbrecht** [sarriaroman/FabricPlugin#58]
I'm using this plugin with my Ionic app on an Android device and I log errors with `window.fabric.Crashlytics.sendNonFatalCrash("ERROR");`

But the errors are only visible in the Fabric UI after killing the app and restarting it. Does anybody have a solution for this?

**Comment by ranvirgorai** [comment]
In your App where u putting this snippet
"window.fabric.Crashlytics.sendNonFatalCrash("ERROR");"

Can you share your complete code of that file.

**Comment by FabianAlbrecht** [comment]
Hi, here is the code:

[app.module.js.zip](https://github.com/sarriaroman/FabricPlugin/files/441964/app.module.js.zip)

**Comment by B-Stewart** [comment]
I'm experiencing the same thing. My guess is that it is because when you use sendCrash() the app is killed and the logs are sent but the nonfatal doesn't kill the app. I'm not sure what the intended behavior is. What is interesting is that it looks the the timestamp is actually created when the code runs, not when the actual nonfatal is sent.
```
.run(function($ionicPlatform, $translate, $cordovaSQLite, $ionicConfig, $cordovaPushV5, $rootScope, AzureService, $window) {
  $ionicPlatform.ready(function() {
$window.fabric.Crashlytics.sendNonFatalCrash("Azure Service Error Non Fatal");
//...
```

**Comment by FabianAlbrecht** [comment]
Just found an interesting sentence in the fabric docs ([Cause a Test Crash](https://docs.fabric.io/apple/crashlytics/test-crash.html#cause-a-test-exception)): 

> Crashes are processed in real-time after you relaunch the app post-crash; make sure you’ve relaunched your app and that it launches fully in the foreground.

So it seems to be expected behavior of the official fabric plugin.
