### ISSUE TITLE
Ionic2 / Fabric

### ISSUE THREAD

**Issue by mehrshadpezeshk** [sarriaroman/FabricPlugin#61]
Hello,

Please let me know how do i need to use the plugin on Ionic2, here's my code : 

import {Component} from '@angular/core';
import {Platform, ionicBootstrap} from 'ionic-angular';
import {StatusBar, Push} from 'ionic-native';
import {TabsPage} from './pages/tabs/tabs';
import {HTTP_PROVIDERS} from '@angular/http';
import {CloudSettings, provideCloud} from '@ionic/cloud-angular';

const cloudSettings: CloudSettings = {
  'core': {
    'app_id': '363e500b'
  }
};

@Component({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  providers: [HTTP_PROVIDERS]
})
export class MyApp {

  private rootPage: any;

  constructor(private platform: Platform) {
    this.rootPage = TabsPage;

```
platform.ready().then(() => {

  StatusBar.styleDefault();

  var push = Push.init({
    ios: {
      alert: "true",
      badge: true,
      sound: 'false'
    }
  });

  push.on('registration', (data) => {
    console.log(data.registrationId);
    alert(data.registrationId.toString());
  });

  push.on('notification', (data) => {
    console.log(data);
    alert("Hi, Am a push notification");
  });

  push.on('error', (e) => {
    console.log(e.message);
  });


});
```

  }
}

ionicBootstrap(MyApp, [provideCloud(cloudSettings)]);

Thanks

**Comment by davidquon** [comment]
I tried bringing this into my Ionic2 application however `cordova-fabric-plugin` seems to have some issues as Crashlytics is able to register the sessions and app with Fabric.io however any crash logging, forced crashes (for testing) or metrics in Answers don't make it through the plugin to Fabric.io.  If there isn't any bandwidth to fix this problem for Ionic2 I'd be interested in helping out if someone can point me in the right direction why these messages are getting lost.

**Comment by ScottMBerger** [comment]
Works fine for me with Android. When using the iOS platform it crashes though.

**Comment by wayoff** [comment]
how to use this on ionic2 project?. . can anyone give an example on importing the `.d.ts` file

**Comment by davidquon** [comment]
For installing Fabric.io:
https://www.npmjs.com/package/cordova-fabric-plugin#install

Then I was able to test Fabric.io and Crashlytics using:
```
(<any>window).fabric.Crashlytics.addLog("about to send a non fatal crash for testing!");
(<any>window).fabric.Crashlytics.sendNonFatalCrash("Error message")
```

Related links that I found useful:
http://stackoverflow.com/a/30740935/6930701
http://stackoverflow.com/a/13480754/6930701
http://stackoverflow.com/a/18475706/6930701

Ionic Info (although these specific versions may not be required):
```
$ ionic info

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62 
```

Lastly I only tested on Android so I'm not 💯 about any other platform.

**Comment by CelsoSantos** [comment]
Any know issues between using this plugin and Ionic-Native TwitterConnect Plugin?

When using both of them my Twitter Login, which happens through TwitterConnect starts giving errors (fortunately, those errors make their way into Crashlytics, so I'm guessing that part is working fine)

**Comment by mebibou** [comment]
For those struggling with this:
1. In your `tsconfig.json` add:
```json
"files": [
    "plugins/cordova-fabric-plugin/typings/cordova-fabric-plugin.d.ts"
  ]
```

2. In `app.module.ts` declare a custom error handler:
```typescript
class MyErrorHandler extends IonicErrorHandler {
  handleError(error) {
    super.handleError(error);

    // example for logging on Android
    fabric.Crashlytics.sendNonFatalCrash(error);
  }
}
```

And use this handler in the providers of the module:
```typescript
providers: [
  {provide: ErrorHandler, useClass: MyErrorHandler}
  ...
]
```

**Comment by ShilpaPrajapati1992** [comment]
@mebibou  : i have use same code but fabric dosen't show app crash in dashboard

**Comment by mebibou** [comment]
@ShilpaPrajapati1992 logging from the front using `sendNonFatalCrash` means you have to toggle the `All Events` dropdown on Fabric Crashlytics, since it logs the error as non-fatal. I've used this code in many apps and I get my errors there
