### ISSUE TITLE
Where to find build secret?

### ISSUE THREAD

**Issue by kenvernaillenvub** [sarriaroman/FabricPlugin#67]
> Setup your Fabric.io account and get your API Key and Build Secret from your [organization page](https://www.fabric.io/settings/organizations/).

The organization page redirects me to https://www.fabric.io/kits/ios/crashlytics.
I can only find the API key there.

**Comment by picassohoang** [comment]
Why close this issue? I encounter same problem. I only see API key. Please have instruction to get API key and API secret step by step

**Comment by kenvernaillenvub** [comment]
Note: If you have never registered an app with your organization, the organization page may redirect you to a wizard preventing you from obtaining your keys. You may be able to obtain your keys from this page. Scroll down to the "Run Script Build Phase" block. The first, shorter string is the API key and the second, longer string is the build secret. If that doesn't work you can follow the wizard and integrate the kit into a dummy "Hello World" project which should then unlock the organization page
