### ISSUE TITLE
sendNonFatalCrash only sends the info to fabric.io after calling sendCrash

### ISSUE THREAD

**Issue by rhinojosahdz** [sarriaroman/FabricPlugin#7]
Hi, first of all, awesome plugin, I have been using it and is very good :)

Right now I have a request to log Non-Fatal Crashes, right now the sendNonFatalCrash function works but you have to call the sendCrash function after it in order for the app to actually send the info to Fabric.

So for example, if I do this:

window.fabric.Crashlytics.addLog('test 1');
window.fabric.Crashlytics.sendNonFatalCrash();
window.fabric.Crashlytics.addLog('test 2');
window.fabric.Crashlytics.sendNonFatalCrash();

and then I wait for and hour, there's no new Non-Fatal crashes reports in Fabric.
I have to call window.fabric.Crashlytics.sendCrash(); to actually see the Non-Fatal crashes in Fabric.

Thanks.
Robert

**Comment by sarriaroman** [comment]
Basically the plugins is doing a direct call to the Fabric SDK using reflection, so... you must check if the Fabric SDK us having the issue you mention. Maybe you can try updating the SDK.

**Comment by rhinojosahdz** [comment]
Still the same.

I did this:

-"cordova platform remove android"
-"cordova platform add android"
-Removed this plugin
-Added this plugin 
-Opened platforms/android project using Android Studio, installed Crashlytics (Answers and Appsee too)

**Comment by jfrumar** [comment]
Sorry to re-open an old issue, but this describes the issue I'm facing perfectly. Is it possible that this is a regression?

**Comment by seza443** [comment]
I installed the plugin and was waiting for my non-fatal crash on Fabric's dashboard...

It appears that the the non-fatals crash are either
- send with the next fatal crash
- send at the next app start

**Comment by jpmsegurado** [comment]
@seza443 that's exactly it, did you implement a workaround or something?

**Comment by seza443** [comment]
@jpmsegurado nope, just live with it 😄
