### ISSUE TITLE
How to get API Key

### ISSUE THREAD

**Issue by seshendramln** [sarriaroman/FabricPlugin#78]
Hi,

I am trying to using fabric.io for my Phonegap application. In that process I have created an account and logged in but I am only onboard page unable to redirect or locate the organisational page for finding the API key. Please help me to find the API key.

Thank you

Regards
Seshendra

**Comment by vasani-arpit** [comment]
![image](https://cloud.githubusercontent.com/assets/6497827/21981719/caf876d4-dc0e-11e6-8fa4-e222c31a7c96.png)
@seshendramln sorry (not sorry) to be a rude but the reason why is right here in the [redme.md](https://github.com/sarriaroman/FabricPlugin#install) in 'Note:' section

![image](https://cloud.githubusercontent.com/assets/6497827/21981824/497dc7de-dc0f-11e6-8ecb-2c2f04417e7a.png)

in that link you will find something like this 
![git support](https://cloud.githubusercontent.com/assets/6497827/21982092/b8d61f2c-dc10-11e6-82a4-ab8560791b4b.jpg)

**Comment by seshendramln** [comment]
@vasani-arpit  Sorry! I have annoyed you. Before I read the whole docs and tried it but I could not able to got the API key that is why the reason I asked you.
