### ISSUE TITLE
Error using window.fabric.*

### ISSUE THREAD

**Issue by ryancrunchi** [sarriaroman/FabricPlugin#8]
Hi, thanks for your work.

When I use your plugin as in your example I get `TypeError: undefined is not an object (evaluating 'window.fabric.Crashlytics')` in console.
I am using iPhone 5 with iOS 9.2, cordova 6.0.0, Crashlytics 3.6.0, Answers 1.1.0.

Edit : Well, I have more informations about this bug. I tested in chrome, everything is ok. When I test in safari 9 (used by iOS), logging `window` object, I find `fabric` as a sub-object that is not undefined. But logging `window.fabric` is undefined. I think the problem comes from the initialization of FabricPlugin variable.

    var FabricPlugin = (function () {
    function FabricPlugin() {
        _classCallCheck(this, FabricPlugin);
    }

    _createClass(FabricPlugin, [{
        key: 'pluginCallName',
        value: function pluginCallName() {
            return 'FabricPlugin';
        }
    }, {
        key: 'execPlugin',
        value: function execPlugin(method, parameters) {
            exec(null, null, this.pluginCallName(), method, [parameters]);
        }
    }]);

        return FabricPlugin;
    })();

    module.exports = new FabricPlugin();

Where you use FabricPlugin variable inside its declaration itself and return it. As it is initializing, FabricPlugin variable is not yet defined when returning it. Some browser may interpret it differently, and return different value. Or not... I don't know, I am not enough friend with javascript.

**Comment by ryancrunchi** [comment]
Still not working with 1.0.0

**Comment by Justin-Credible** [comment]
Can you provide steps to reproduce the issue?

I've been using the plugin in production on both Android and iOS without any issues.

<img width="563" alt="screen shot 2016-03-01 at 8 26 59 am" src="https://cloud.githubusercontent.com/assets/1243565/13433603/729c9f26-df87-11e5-947b-5009a3a68b41.png">

**Comment by ryancrunchi** [comment]
Hi, 
I first tried `cordova plugin add https://github.com/sarriaroman/FabricPlugin@1.0.0 --variable FABRIC_API_KEY=xxxxxxxxxxxxxxxxx --variable FABRIC_API_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxx`
I got

    Error: Failed to fetch plugin https://github.com/sarriaroman/FabricPlugin@1.0.0 via git. Either there is a connection problems, or plugin spec is incorrect:
    Error: git: Command failed with exit code 128 Error output:
    Cloning into '/var/folders/sg/5y2wlpsn6jbd7yp1zlvvcsf00000gn/T/git/1456906754536'...
    fatal: unable to access 'https://github.com/sarriaroman/FabricPlugin@1.0.0/': The requested URL returned error: 400

So I remove @1.0.0 in command : `cordova plugin add https://github.com/sarriaroman/FabricPlugin --variable FABRIC_API_KEY=xxxxxxxx --variable FABRIC_API_SECRET=xxxxxxxxxxxxxxxxxxxx`
And the plugin installed correctly.

I then log `console.log(window);`and `console.log(window.fabric);` after `deviceready`event.
The first log shows all window object including `fabric` : 
<img width="291" alt="capture d ecran 2016-03-02 a 09 30 18" src="https://cloud.githubusercontent.com/assets/4698648/13454830/f90ceae8-e059-11e5-8b8e-f8daaf28db6b.png">

But the second log shows `undefined` : 
<img width="109" alt="capture d ecran 2016-03-02 a 09 35 42" src="https://cloud.githubusercontent.com/assets/4698648/13454859/2bdc6084-e05a-11e5-9e88-2d993230e293.png">

I am using Safari 9.0.3 on el capitan 10.11.3, cordova 6.0.0, iOS 9.2.1. Also not working on windows 8 safari 5.1.7. But working fine on chrome any OS.

**Comment by Justin-Credible** [comment]
It looks like I made a typo in the readme; the version is specified using a pound instead of @ sign. So `#1.0.0` instead of `@1.0.0`. That will fix your first problem of a 404 during install. I recommend trying again with that.

**Comment by ryancrunchi** [comment]
With `#1.0.0` is installing fine. But still the same error at runtime, only Safari. Sorry, I can't tell so much more to find a solution. I'm searching when I have time.
