### ISSUE TITLE
iOS Plugin not being called

### ISSUE THREAD

**Issue by Iyashu5040** [sarriaroman/FabricPlugin#81]
In my JS code I have 
```
         console.log(" --- CALLING CRASHLYTICS --- ");
        (<any>window).fabric.Crashlytics.addLog(err.message);
        (<any>window).fabric.Crashlytics.recordError(err.message, -1);
        console.log(" --- CRASHLYTICS DONE --- "); 
```

I see the CALLING CRASHLYTICS console output and then nothing. There is no more console output and the error never gets logged to the Crashlytics dashboard.

I've gone into the `FabricPlugin.m` code and added calls to NSLog in methods such as `addLog` and `recordError` but these logs never get output.

Calls to `(<any>window).fabric.Crashlytics.sendCrash();` do cause en exception but also don't show up on the Crashlytics dasboard. This only works if `sendCrash` is the first method I call, if I call `addLog` before, I end with nothing happening again.

**Comment by sarriaroman** [comment]
You need to check on "Build Phases" in section "Compile Sources" if FabricPlugin.m is added on the list. Sometimes Cordova do not add the m to sources and that is the problem. If the problem persist you will need remove and re add the plugin.

**Comment by Iyashu5040** [comment]
@sarriaroman I've checked the Compile Sources and FabricPlugin.m is in the list. I've tried removing and re-adding the plugin but it still doesn't work. I've added an NSLog in the `(void)pluginInitialize` and that gets output to the console when the app starts.

**Comment by sarriaroman** [comment]
Can you share the exact code you are using from JS to call the plugin?

```
(<any>window).fabric.Crashlytics.addLog(err.message);
        (<any>window).fabric.Crashlytics.recordError(err.message, -1);
```

must be

```
window.fabric.Crashlytics.addLog(err.message);
window.fabric.Crashlytics.recordError(err.message, -1);
```

**Comment by Iyashu5040** [comment]
@sarriaroman Sorry for the late reply. I'm using this plugin in a TypeScript Angular 2 app. I cast `window` to `any` so that the TS compiler will allow me to use the `fabric` property on `window`. `err.message` is just a string set to "test message" at the moment. I am calling the plugin from a button click event.

**Comment by Iyashu5040** [comment]
Maybe the issue is that Fabric has been updated?

**Comment by Iyashu5040** [comment]
I've solved the issue. Turns out I wasn't waiting for device ready, rookie mistake, sorry.
