### ISSUE TITLE
Deprecated version of Crashlytics

### ISSUE THREAD

**Issue by wigvp** [sarriaroman/FabricPlugin#82]
The used Crashlytics version isn't up-to-date anymore: https://fabric.io/kits/android/crashlytics/update

**Comment by sarriaroman** [comment]
You can try with cordova plugin add https://github.com/sarriaroman/FabricPlugin the android version is updated on master. Please let me know if works

**Comment by wigvp** [comment]
@sarriaroman Seems to work. Thank you.
