### ISSUE TITLE
Can I share FABRIC_API_KEY and FABRIC_API_SECRET publicly? 

### ISSUE THREAD

**Issue by seza443** [sarriaroman/FabricPlugin#89]
Hi,

When installing the plugin, it adds FABRIC_API_KEY and FABRIC_API_SECRET in the `config.xml`.
Can I checkout this file publicly on Github without worrying about those secrets ?

Thanks

**Comment by seza443** [comment]
Reading from Fabric's forums, I think I can.

Letting this open until someone confirm 😸

**Comment by sarriaroman** [comment]
API keys are secret only for you, so it's not recommended

**Comment by seza443** [comment]
Ok thanks
