### ISSUE TITLE
Property 'fabric' does not exist on type 'Window'.

### ISSUE THREAD

**Issue by rmelfi** [sarriaroman/FabricPlugin#92]
My error is Property 'fabric' does not exist on type 'Window'.

What happens?

Tks

**Comment by sarriaroman** [comment]
You need to declare the property fabric in your declaration.d.ts file because TypeScript is not able to find be object himself

**Comment by rmelfi** [comment]
Do you have examples?

**Comment by sarriaroman** [comment]
In your declaration file copy the next

```
interface Window { fabric: any; }
```

**Comment by rmelfi** [comment]
Sorry.

i'm very noob

now my error is 

Error in ./MyApp class MyApp - caused by: Cannot read property 'Crashlytics' of undefined

**Comment by paishin** [comment]
I have the same problem, property fabric is not exposed on window. Any solutions?

**Comment by paishin** [comment]
It looks like it is exposed when running on a device but not when using ionic serve

**Comment by sarriaroman** [comment]
The plugin will only work on native. You can check if you are in Cordova with ionic before to call the plugin

**Comment by paishin** [comment]
I think this should be in the documentation...I spent so much time trying to figure this out :) Thank you for a great plugin.
